In [1]:
import numpy as np

In [2]:
a = np.ones((2,5), dtype = np.float32)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
b = np.zeros((3,3), dtype = np.float32)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c = np.array([[1,2,3],[4,5,6]])
print(c.ndim, c.shape, c.dtype)

2 (2, 3) int32


In [7]:
d = np.arange(5,10)
print(d)

[5 6 7 8 9]


In [9]:
e = np.arange(1,10,2)
print(e)

[1 4 7]


In [11]:
f = np.linspace (2.0, 3.0, num=5, endpoint=False)
print(f)

[2.  2.2 2.4 2.6 2.8]


In [12]:
f = np.linspace (2.0, 3.0, num=5)
print(f)

[2.   2.25 2.5  2.75 3.  ]


In [13]:
f = np.linspace (2.0, 3.0)
print(f)

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ]


In [15]:
a = np.ones((3,1))
print(a)
b = np.zeros((3,2))
print(b)
c = np.concatenate([a,b], axis=1)
print(c)

[[1.]
 [1.]
 [1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [16]:
a = np.ones((1,3))
print(a)
b = np.zeros((3,3))
print(b)
c = np.concatenate([a,b], axis=0)
print(c)

[[1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a = np.ones((2,2))
print(a)
b = np.zeros_like(a)
print(b)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [19]:
x = np.random.rand(3,5)
print(x)

[[0.47429834 0.97871245 0.42812239 0.30761135 0.69436879]
 [0.82528608 0.07181598 0.57737078 0.43372781 0.25280539]
 [0.66931101 0.69281982 0.21688674 0.87733977 0.38484968]]


In [21]:
x = np.random.randint(5, 10, size=(2, 2))
print(x)

[[5 5]
 [7 9]]


In [23]:
p = np.array([[1,2,3,4], [5,6,7,8]])
print(p)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
p[0][1]

2

In [25]:
p[0:1,0:3]

array([[1, 2, 3]])

In [30]:
y = np.array([1,2,3,4,5,6,7,8,9])
#o = np.array([1,4,7])
s = y[[1,4,7,4,1]]
print(s)

[2 5 8 5 2]
