In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
b = a * 2
print(b)

[ 2  4  6  8 10]


In [3]:
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])
c = a+b
print(c)


[ 3  6  9 12]


In [4]:
d = np.add(a,c)
print(d)

[ 4  8 12 16]


In [3]:
import numpy as np
e = np.array([2,3,4,5,6,7,8])
b = np.array([2,4,6,8])
f = e+b
print(f)

ValueError: operands could not be broadcast together with shapes (7,) (4,) 

In [7]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
x.shape


(3, 2)

In [9]:
i = np.array([10,20])
print(i)
i.shape

[10 20]


(2,)

In [10]:
y = x + i
print(y)

[[11 22]
 [13 24]
 [15 26]]


In [14]:
k = np.reshape(y,(2,3))
print(k)

[[11 22 13]
 [24 15 26]]


In [16]:
k = np.resize(y,(3,4))
print(k)

[[11 22 13 24]
 [15 26 11 22]
 [13 24 15 26]]


In [17]:
k = np.reshape(y,(2,3), order="F")
print(k)

[[11 15 24]
 [13 22 26]]


In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
z = x.flatten()
print(z)

[1 2 3 4 5 6 7 8 9]


In [61]:
b = np.ravel(z)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
m = np.transpose(x)
print(m)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [37]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Refer to `numpy.ndarray.transpose` for full documentation.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    ndarray.transpose : Equivalent method
    moveaxis
    argsort
    
    N

In [41]:
p = np.array([1,2,3,4,5,6,7])
q = np.insert(p,3,10)
print(q)

[ 1  2  3 10  4  5  6  7]


In [45]:
o = np.append(p,8)
print(o)

[1 2 3 4 5 6 7 8]


In [43]:
n = np.delete(p,3) # you delete number on index 3

In [44]:
print(n)

[1 2 3 5 6 7]


In [46]:
s = np.array([[1,2],[2,2]])
t = np.array([[2,3],[1,2]])
u = s*t
print(u)

[[2 6]
 [2 4]]


In [48]:
v = np.matrix('1 2;3,4')
print(v)

[[1 2]
 [3 4]]


In [50]:
w = np.linalg.inv(v)
print(w)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [51]:
mul = v*w
print(mul)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [54]:
z = np.linalg.matrix_power(v,-2)
print(z)

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [59]:
aa=np.array([[3,1],[1,2]])
bb = np.array([9,8])
cc=np.linalg.solve(aa,bb)
print(cc)

[2. 3.]


In [60]:
dd = np.linalg.det(aa)
print(dd)

5.000000000000001


In [73]:
b = np.array([1,2,3,4,5])
c = np.array([11,12,13,14,15])
d = np.concatenate((b,c), axis =0)
print(d)
d.shape

[ 1  2  3  4  5 11 12 13 14 15]


(10,)