In [1]:
import numpy as np

a = np.arange(30,70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [4]:
import numpy as np

b = np.array([[1,2,3,4,5],[6,7, 8, 9, 10]])
c = np.array([[11,12,13,14,15],[1,2,3,4,5]])
d = np.concatenate((b,c), axis=0)
#d = np.concatenate((b,c), axis=1)
print(d)
d.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 1  2  3  4  5]]


(4, 5)